[package]
name = "revm-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"

[dependencies.revm]
path = "revm/crates/revm"
features = ["std"]