[profile.default]
src = "benchmarks"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
# Disable metadata to prevent issues with strict EVM implementations
bytecode_hash = "none"
cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
